title: Portfolio
logo: assets/images/profile.jpg
description: Believe 🍁
theme: jekyll-theme-minimal

# Github and twitter are optional:
minima:
  social_links:
    twitter: rednafi
    github: rednafi

# Set this to true to get LaTeX math equation support
use_math: true

# Set this to true to display the summary of your blog post under your title on the Home page.
show_description: true

# Set this to true to display image previews on home page, if they exist
show_image: false

# Set this to true to display tags on each post
show_tags: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics: UA-160409032-1

exclude:
  - docker-compose.yml
  - action.yml
  - Makefile

# this setting allows you to keep pages organized in the _pages folder
include:
  - _pages

# Everything below here should be left alone. Modifications may break fastpages
future: true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-remote-theme

remote_theme: jekyll/minima

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge